CREATE OR REPLACE FUNCTION IS_NUMERIC( P_STR IN VARCHAR2 ) RETURN NUMBER
AUTHID CURRENT_USER IS
    L_NUM NUMBER;
BEGIN
    L_NUM := TO_NUMBER( P_STR );
    RETURN 1;
EXCEPTION
    WHEN VALUE_ERROR
    THEN
    RETURN 0;
END;
/

EXIT SUCCESS;